### ISSUE TITLE
1.5 dependencies

### ISSUE THREAD

**Issue by walker-dev** [DaedalusGame/EmbersRekindled#36] opened 2018-08-22 01:48 UTC
Mystic Mechanics
Optional or Required?

> java.lang.NoClassDefFoundError: mysticalmechanics/api/IGearBehavior
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:131)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:80)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: mysticalmechanics.api.IGearBehavior
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Caused by: java.lang.NullPointerException

[crash-2018-08-22_03.43.25-server.txt](https://github.com/DaedalusGame/EmbersRekindled/files/2308617/crash-2018-08-22_03.43.25-server.txt)

**Comment by DaedalusGame** [comment] 2018-08-22 01:55
Dupe of #35

**Closed as completed by DaedalusGame** 2018-08-22 01:55 UTC
