### ISSUE TITLE
Black smoke and a sound when breaking blocks

### ISSUE THREAD

**Issue by Scrayyg** [DaedalusGame/EmbersRekindled#75] opened 2018-10-01 00:43 UTC
Minecraft: 1.12.2
Forge: 14.23.4.2765
Mods: EmbersRekindled-1.9
Baubles-1.12-1.5.2

Issue: Whenever a block is broken it creates some black particles and makes a sound effect. It only happens if both mods are in and I tested it with all other mods removed. 
![2018-09-30_20 26 16](https://user-images.githubusercontent.com/34176694/46265035-d7695600-c4f0-11e8-80d7-fde35f3e87e9.png)

**Comment by DaedalusGame** [comment] 2018-10-01 00:51
Duplicate of #71

**Closed as completed by DaedalusGame** 2018-10-01 00:51 UTC
