### ISSUE TITLE
Ember Gague on Reservoir Crash

### ISSUE THREAD

**Issue by Levion1** [DaedalusGame/EmbersRekindled#191] opened 2019-09-10 21:36 UTC
[crash-2019-09-10_14.46.28-server.txt](https://github.com/DaedalusGame/EmbersRekindled/files/3597762/crash-2019-09-10_14.46.28-server.txt)
[crash-2019-09-10_14.48.14-server.txt](https://github.com/DaedalusGame/EmbersRekindled/files/3597764/crash-2019-09-10_14.48.14-server.txt)

When putting an Ember Gague over one of the outlets on a Caminite valve, it crashes the game.
The world from there on cannot be re-opened, as it instantly crashes the game, hence the second file.

**Comment by DaedalusGame** [comment] 2019-09-11 10:33
Dupe of #158

**Closed as completed by DaedalusGame** 2019-09-11 10:33 UTC
