### ISSUE TITLE
Crash with a tinker's lens on offhand while staring at a caminite valve

### ISSUE THREAD

**Issue by cabaleiro** [DaedalusGame/EmbersRekindled#188] opened 2019-08-24 18:55 UTC
https://paste.dimdev.org/jowasahici.mccrash

Forge 14.23.5.2838
Embers 1.13-hotfix2
Mystical Mechanics 0.10

(MIGHT BE RELEVANT) playing on a self-hosted server (SMP).

To reproduce, put a tinker's lens on the offhand and then look towards a caminite valve sitting on top of a caminite ring / reservoir.

**Comment by DaedalusGame** [comment] 2019-09-11 10:33
Dupe of #158

**Closed as completed by DaedalusGame** 2019-09-11 10:33 UTC
