### ISSUE TITLE
long load times with wearable backpacks (x-mod)

### ISSUE THREAD

**Issue by mailleseraph** [DaedalusGame/EmbersRekindled#148] opened 2019-04-04 14:53 UTC
Hello, when loading up a world with wearable backpacks there is a problem with this mod and wearable backpacks that causes significantly long load times in recipe loading. problem exists with just embers rekindled, JEI, and wearable backpacks, but the more mods there are the longer the load problem.

the log shows:

https://pastebin.com/ijfgMemq

versions:
forge 14.23.5.2823
wearable backpacks: 1.12.2- 3.1.3
embers rekindled: 1.13
edit: jei version: 4.15.0.271

edit: is there a way to blacklist items for anvil breakdown?

**Comment by mailleseraph** [comment] 2019-04-04 14:53
issue opened on wearable backpacks: https://github.com/copygirl/WearableBackpacks/issues/108

**Comment by DaedalusGame** [comment] 2019-04-04 15:00
dupe of #143

**Closed as completed by DaedalusGame** 2019-04-04 15:00 UTC
