### ISSUE TITLE
Placing an Ember Dial on a Fluid Valve Crashes the Game

### ISSUE THREAD

**Issue by Calemi** [DaedalusGame/EmbersRekindled#179] opened 2019-07-25 07:16 UTC
Whenever an Ember Dial is placed on a Fluid Valve, it will crash the game. I tested this on a server and client, and they both result in the same fate. The crash is so bad that is will make playing that same world impossible without older backups. Since the block is registered as a placed block right before it crashes, the block is saved there so whenever I load up the world (server and client) it crashes again.

Note: Obviously an Ember Dial is the wrong Dial to place on a Fluid Valve, so it doesn't completely break the Reservoir from being used.

Extra Note: Fluid Dials will work fine when placed. It is only the Ember Dial that causes the crash.

I just started getting into this mod, and I'm really enjoying it, but I almost lost my world because of it. I hope this gets fixed soon because I want to get back into playing around with it.

Thanks, Calemi

**Comment by DaedalusGame** [comment] 2019-08-01 11:51
Dupe of  #158

**Closed as completed by DaedalusGame** 2019-08-01 11:51 UTC
