### ISSUE TITLE
Constructing(Initialising) Crash

### ISSUE THREAD

**Issue by SSKirillSS** [DaedalusGame/EmbersRekindled#41] opened 2018-08-22 08:51 UTC
Client crashed when I`m starting launch the game.

Mods:
Baubles-1.12-1.5.2
EmbersRekindled-1.5
Forge:
1.12.2-forge1.12.2-14.23.4.2749
Crash-report: https://pastebin.com/Wdey51ec

**Comment by DaedalusGame** [comment] 2018-08-22 08:52
Dupe of #35

**Closed as completed by DaedalusGame** 2018-08-22 08:52 UTC
