### ISSUE TITLE
Visual glitch with Thaumcraft casters gauntlet

### ISSUE THREAD

**Issue by blueblaise** [DaedalusGame/EmbersRekindled#277] opened 2021-01-02 05:06 UTC
the gauntlet for thaumcraft is missing a portion of the texture is invisible. thaumcrafts gauntlet visuals are normal on the original embers but in this embers it has this issue
![2021-01-01_23 05 28](https://user-images.githubusercontent.com/57926135/103451138-f170e080-4c85-11eb-896b-75a74312dbd3.png)
versions
Minecraft:1.12.2
Embers Rekindeled:1.15
Forge:14.23.5.2855
Thaumcraft:6.1BETA26
Baubles:1.5.2

**Comment by blueblaise** [comment] 2021-01-02 05:16
just checked Embers Rekindeled 1.14hotfix fixed the visual glitch

**Comment by DaedalusGame** [comment] 2021-01-02 13:28
Dupe of #276

**Closed as completed by DaedalusGame** 2021-01-02 13:28 UTC
