### ISSUE TITLE
Caminite Valve endlessly crashes world

### ISSUE THREAD

**Issue by LihrhaWolfe** [DaedalusGame/EmbersRekindled#201] opened 2019-10-26 17:30 UTC
When using integrated tunnels to export any fluid into a reservoir through the valve it permanently crashes the world.  It does not do this however when using the embers fluid pipes to input any fluid.

in case the crash report is needed here is a pastebin link.
https://pastebin.com/72CwFn2Y

I hope the issue is possible to fix, otherwise this sucks.

**Comment by indygwyn** [comment] 2019-11-04 01:19
I think I might also have an issue similar to this, MP world crashed as soon as I connected a a fluid pipe to a caminite valve and I've been unable to get the world to come back up in MP or in SP
https://paste.dimdev.org/luvivuroqa.mccrash

Update: nope, mine was a ticking entity caused by powering an item extractor attached to a caminite valve instead of a fluid extractor. fixed via forge remove ticking entity configs

**Comment by DaedalusGame** [comment] 2020-03-13 09:49
Dupe of #158

**Closed as completed by DaedalusGame** 2020-03-13 09:49 UTC
