### ISSUE TITLE
Game crash when Tinker lens "hit" caminite valve

### ISSUE THREAD

**Issue by SiriosDev** [DaedalusGame/EmbersRekindled#214] opened 2019-12-14 22:19 UTC
It's litteraly all in the title, this is the crash report
[crash-2019-12-14_23.16.27-client.txt](https://github.com/DaedalusGame/EmbersRekindled/files/3964400/crash-2019-12-14_23.16.27-client.txt)

**Comment by DaedalusGame** [comment] 2020-03-13 10:38
Dupe of #158

**Closed as completed by DaedalusGame** 2020-03-13 10:38 UTC
