### ISSUE TITLE
Caminite Valve issues

### ISSUE THREAD

**Issue by RauzKindred** [DaedalusGame/EmbersRekindled#192] opened 2019-09-11 01:08 UTC
I use embers through a mod pack and I seem to be having a strange crashing issue. Every time I attempt to use the caminite valve add-on for the reservoir, the game has a lag spike and then crashes.
I attached the crash report, maybe you can help me figure out if its a mod argument or if there is something else causing it. Thankfully its not a needed add-on so not a big issue but figured I'd report it either way.
[crash-2019-09-10_20.58.42-client.txt](https://github.com/DaedalusGame/EmbersRekindled/files/3598344/crash-2019-09-10_20.58.42-client.txt)

**Comment by DaedalusGame** [comment] 2019-09-11 10:33
Dupe of #158

**Closed as completed by DaedalusGame** 2019-09-11 10:33 UTC
