### ISSUE TITLE
Server crashes when using tinkers lens on caminite valve.

### ISSUE THREAD

**Issue by jritter96** [DaedalusGame/EmbersRekindled#195] opened 2019-09-28 03:53 UTC
As soon as the crosshair moves onto the output block of the valve, the game crashes with a null pointer exception. The lens works fine on the other parts of the reservoir.

 Crash report: https://paste.dimdev.org/xaxiqodife.mccrash

**Comment by DaedalusGame** [comment] 2020-03-13 09:49
Dupe of #158

**Closed as completed by DaedalusGame** 2020-03-13 09:49 UTC
