### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MrTubzy456** [DaedalusGame/EmbersRekindled#74] opened 2018-09-30 19:51 UTC
Forge version: 14.23.4.2760
Embers version: 1.9
Soot version: 1.5

I've tested on both client and server, and I've gotten the same crash report on both. If I downgrade to the 1.8 version of Embers Rekindled both run just fine. I'm posting here because it's happening when I upgraded to the new version of Embers Rekindled. If you want me to post it on the Soot github I can do that.

Crash report:  https://pastebin.com/GB2yHrE0

**Comment by DaedalusGame** [comment] 2018-09-30 20:04
Duplicate of #72

**Closed as completed by DaedalusGame** 2018-09-30 20:04 UTC
